config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get '/', to: "statics#index", as: "home"

  resources :users, only: [:new, :create, :show]
  resources :events, only: [:index, :show, :new, :create]

  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
# frozen_string_literal: true

class Event < ApplicationRecord
  belongs_to :creator, class_name: 'User'
  has_many :user_events
  has_many :attendees, through: :user_events, source: :user
  scope :upcoming, -> { where('date > ?', Time.zone.now) }
  scope :past, -> { where('date <= ?', Time.zone.now) }

  validates :date, presence: true
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_many :events, foreign_key: 'creator_id', class_name: 'Event'
  has_many :user_events
  has_many :attended_events, through: :user_events, source: :event

  before_save { email.downcase! }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i.freeze

  validates :name, presence: true, length: { maximum: 50, minimum: 2 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }

  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
end

app/models/user_event.rb
# frozen_string_literal: true

class UserEvent < ApplicationRecord
  belongs_to :user
  belongs_to :event
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  include SessionsHelper
end

app/controllers/events_controller.rb
# frozen_string_literal: true

class EventsController < ApplicationController
  def index
    @events_past = Event.past
    @events_upcoming = Event.upcoming
  end

  def show
    @event = Event.find_by(id: params[:id])
  end

  def new
    @event = Event.new
  end

  def create
    if logged_in?
      current_user.events.build(event_params)
      current_user.save
      redirect_to events_path
    else
      redirect_to login_path
    end
  end

  private

  def event_params
    params.require(:event).permit(:name, :description, :date)
  end
end

app/controllers/sessions_controller.rb
# frozen_string_literal: true

class SessionsController < ApplicationController
  def new; end

  def create
    @user = if !params[:user_id]&.empty?
              User.find_by(id: params[:user_id])
            elsif !params[:name]&.empty?
              User.find_by(name: params[:name])
            end

    if @user
      log_in(@user)
      redirect_to user_path(@user)
    else
      flash.now[:danger] = 'user not found'
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to home_path
  end
end

app/controllers/statics_controller.rb
# frozen_string_literal: true

class StaticsController < ApplicationController
  def index; end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in(@user)
      flash[:success] = 'User Created'
      redirect_to user_path(@user)
    else
      flash.now[:danger] = 'Some Errors in Form'
      render 'new'
    end
  end

  def show
    @user = params[:id] ? User.find_by(id: params[:id]) : nil
    if @user
      @created_upcoming_events = @user.events.upcoming
      @created_past_events = @user.events.past
      @attended_upcoming_events = @user.attended_events.upcoming
      @attended_past_events = @user.attended_events.past
    else
      flash[:danger] = 'User not found'
      redirect_to home_path
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/events_helper.rb
# frozen_string_literal: true

module EventsHelper
end

app/helpers/sessions_helper.rb
# frozen_string_literal: true

module SessionsHelper
  def logged_in?
    !current_user.nil?
  end

  def current_user
    @current_user ||= (session[:user_id] ? User.find(session[:user_id]) : nil)
  end

  def log_in(user)
    session[:user_id] = user.id
  end

  def sign_out
    session[:user_id] = nil
    @current_user = nil
  end
end

app/helpers/statics_helper.rb
# frozen_string_literal: true

module StaticsHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/events/_event.html.erb
<tr class="cursor-pointer" onclick="location.href = '<%= event_path(event.id) %>';">
  <td><%= event.id %></td>
  <td><%= event.name %></td>
</tr>

app/views/events/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12">
      <h1>
        Event's List
        &nbsp;&nbsp;&nbsp;
        <% if logged_in? %>
          <%= link_to "New Event", new_event_path, class: "btn btn-success ml-auto" %>
        <% end %>
        </h1>
      <hr>
    </div>
    <div class="col-sm-12 col-md-6">
      <h3>Upcoming Events</h3>
      <table class="table table-striped table-hover">
        <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">Name</th>
          </tr>
        </thead>
        <tbody>
          <%= render @events_upcoming  %>
        </tbody>
      </table>
    </div>
    <div class="col-sm-12 col-md-6">
      <h3>Previous Events</h3>
      <table class="table table-striped table-hover">
        <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">Name</th>
          </tr>
        </thead>
        <tbody>
          <%= render @events_past  %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/events/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-12 col-md-8 col-lg-6 offset-md-2 offset-lg-3 mb-3">
      <h1>Create Event</h1>
    </div>
    <div class="col-12 col-md-8 col-lg-6 offset-md-2 offset-lg-3">
      <%= form_with model: @event, local:true do |f| %>
        <%= f.label "Name" %>
        <%= f.text_field :name, class: "form-control" %>

        <%= f.label "Date" %>
        <%= f.datetime_local_field :date, class: "form-control" %>

        <%= f.label "Description" %>
        <%= f.text_area :description, class: "form-control" %>
        <br>
        <%= f.submit "Create Event", class:"btn btn-success" %>
      <% end  %>
    </div>
  </div>
</div>

app/views/events/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12">
      <h1>Event description</h1>
      <p>
        <b>Creator:</b><%= @event.creator.name %><br>
        <b>Name of Event:</b><%= @event.name%><br>
        <b>Description:</b><%= @event.description %><br>
      </p>
      <hr>
    </div>
    <div class="col-sm-12 col-md-6">

      <h3>Event's Attendees</h3>
      <table class="table table-striped table-hover">
        <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">Name</th>
          </tr>
        </thead>
        <tbody>
          <% @event.attendees.each do |attendee| %>
            <tr class="cursor-pointer" onclick="location.href = '<%= user_path(attendee.id) %>';">
              <td><%= attendee.id %></td>
              <td><%= attendee.name %></td>
            </tr>
          <% end  %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-light mb-5 bg-dark">
  <a class="navbar-brand" href="/">Private Events</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item">
        <a class="nav-link" href="/">Home</a>
      </li>
      <li class="nav-item">
        <%= link_to "Events", events_path, class: "nav-link" %>
      </li>
      <li class="nav-item d-none d-lg-block disabled">
        <span class="nav-link">|</span>
      </li>
      <% if logged_in? %>
      <li class="nav-item">
        <%= link_to 'Profile', user_path(current_user), class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to 'Sign Out', logout_path, method: :delete, class: "nav-link" %>
      </li>
      <% else %>
      <li class="nav-item">
        <%= link_to  "Log In", login_path, class: "nav-link" %>
      </li>
        <li class="nav-item">
          <%= link_to  "Sign Up", new_user_path , class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= render 'shared/msg' if !flash.empty? %>

    <%= yield %>
  </body>
</html>

app/views/shared/_msg.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-12">
      <% flash.each  do |key, value| %>
        <div class="alert alert-<%= key %>" role="alert">
          <%= value %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/statics/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12">
      <h1>Private Events</h1>
      <p>the best web in the world!</p>
    </div>

  </div>
</div>

app/views/users/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-12 col-md-8 col-lg-6 offset-md-2 offset-lg-3 mb-3">
      <h1>Sign Up</h1>
    </div>
    <div class="col-12 col-md-8 col-lg-6 offset-md-2 offset-lg-3">
      <%= form_with model: @user, local:true do |f| %>
        <%= f.label "Name" %>
        <%= f.text_field :name, class: "form-control" %>

        <%= f.label "Email" %>
        <%= f.text_field :email, class: "form-control" %>

        <%= f.label "Password" %>
        <%= f.password_field :password, class: "form-control" %>

        <%= f.label "Confirm Password" %>
        <%= f.password_field :password_confirmation,  class: "form-control" %>
        <br>
        <%= f.submit "Create Account", class:"btn btn-success" %>
      <% end  %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12">
      <h1>Users Profile</h1>
      <h2><%= @user.name %></h2>
      <p>this is a nice profile</p>
      <hr>
    </div>
    <div class="col-sm-12 col-md-6">

      <h3>Events created</h3>
      <br>
      <h4>Upcoming Events</h4>
      <table class="table table-striped table-hover">

        <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">Name</th>
          </tr>
        </thead>
        <tbody>
          <%= render @created_upcoming_events %>
        </tbody>
      </table>

      <h4>Previous Events</h4>
      <table class="table table-striped table-hover">

        <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">Name</th>
          </tr>
        </thead>
        <tbody>
          <%= render @created_past_events %>
        </tbody>
      </table>
    </div>
    <div class="col-sm-12 col-md-6">

      <h3>Events Attending</h3>
      <br>
      <h4>Upcoming Events</h4>
      <table class="table table-striped table-hover">
        <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">Name</th>
          </tr>
        </thead>
        <tbody>
          <%= render @attended_upcoming_events %>
        </tbody>
      </table>

      <h4>Previous Events</h4>
      <table class="table table-striped table-hover">
        <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">Name</th>
          </tr>
        </thead>
        <tbody>
          <%= render @attended_past_events %>
        </tbody>
      </table>
    </div>
  </div>
</div>